# Generated by Django 4.2.1 on 2023-06-20 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('descripcion', models.CharField(max_length=400, verbose_name='Descripción')),
                ('marca', models.CharField(max_length=80, verbose_name='Marca')),
                ('precio', models.IntegerField(default=0, verbose_name='Precio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID Sucursal')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de Sucursal')),
                ('direccion', models.CharField(max_length=120, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'ordering': ['id_sucursal'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('fecha_pedido', models.DateField(auto_now_add=True, verbose_name='Fecha del Pedido')),
                ('estado', models.CharField(default='Pendiente', max_length=10, verbose_name='Estado')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total del Pedido')),
                ('productos', models.ManyToManyField(through='bodega.DetallePedido', to='bodega.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.sucursal')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['id_pedido'],
            },
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.pedido'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.producto'),
        ),
    ]
