# Generated by Django 4.2.1 on 2023-06-05 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pedido', models.CharField(max_length=9, unique=True, verbose_name='ID Pedido')),
                ('fecha_pedido', models.DateField(auto_now_add=True, verbose_name='Fecha del Pedido')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Enviado', 'Enviado'), ('Completado', 'Completado')], default='Pendiente', max_length=10, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['id_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('descripcion', models.CharField(max_length=400, verbose_name='Descripción')),
                ('marca', models.CharField(max_length=80, verbose_name='Marca')),
                ('precio', models.IntegerField(default=0, verbose_name='Precio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sucursal', models.IntegerField(verbose_name='ID Sucursal')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de Sucursal')),
                ('dirección', models.CharField(max_length=120, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'ordering': ['id_sucursal'],
            },
        ),
        migrations.CreateModel(
            name='ProductoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoPedido', to='bodega.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoPedido', to='bodega.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(through='bodega.ProductoPedido', to='bodega.producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.sucursal'),
        ),
    ]
