# Generated by Django 4.2.1 on 2023-06-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursal',
            old_name='dirección',
            new_name='direccion',
        ),
    ]
