# Generated by Django 4.2.1 on 2023-06-20 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_pedido',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='id_sucursal',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID Sucursal'),
        ),
    ]
