# Generated by Django 4.2.1 on 2023-06-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductoPedido',
            new_name='DetallePedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total del Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=10, verbose_name='Estado'),
        ),
    ]
