# Generated by Django 4.2.1 on 2023-06-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='productos/default.png', upload_to='productos/', verbose_name='Imagen'),
        ),
    ]
