# Generated by Django 4.2.1 on 2023-06-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_producto_fecha_creacion_alter_pedido_id_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Pedido'),
        ),
    ]
