# Generated by Django 4.2.1 on 2023-05-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_alter_usuario_options_producto_stock_usuario_rut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=40, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
    ]
