# Generated by Django 4.2.1 on 2023-05-26 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['email'], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
