# Generated by Django 4.2.1 on 2023-06-01 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_alter_producto_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
