# Generated by Django 4.2.1 on 2023-06-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0006_alter_producto_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_seguimiento',
            field=models.CharField(default='Pendiente', max_length=16, verbose_name='Código de Seguimiento'),
        ),
    ]
